name: Node.js CI
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Ruby
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          ruby-version: '3.3.22' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
      - run: sudo gem install bundler && sudo bundle install
      - run: npm install
      - run: npm run build
      - name: Jekyll Deploy Action
        uses: jeffreytse/jekyll-deploy-action@v0.4.0
        with:
          JEKYLL_ENV: production
          GH_PAGES_TOKEN: "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"
